# Generated by Django 4.2.4 on 2023-10-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='email',
        ),
    ]
